---
language: python

python:
  - 3.7
  - 3.8

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install pre-commit

script:
  - SKIP=no-commit-to-branch pre-commit run --all-files
